version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: lcg_backend
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/static:/app/static
    networks:
      - lcg_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: https://backend.makepost.pro
    container_name: lcg_frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - lcg_network
    depends_on:
      - backend

networks:
  lcg_network:
    driver: bridge
